# Maintainer: gosha
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=typecat-bin
pkgver=0.1.0
pkgrel=1
pkgdesc="terminal typing test"
url="https://pndrs.codes"
license=("MIT")
arch=("x86_64")
provides=("typecat")
conflicts=("typecat")
source=("https://github.com/pandaroses/typecat/releases/download/v$pkgver/typecat-$pkgver-x86_64.tar.gz")
sha256sums=("62cf8d583a5ca2cd7f5f7bcaf67a0c50e878b6e2884dda0aeb0bae5b92587efc")

package() {
    install -Dm755 typecat -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
